### ISSUE TITLE
Error from max_utr

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#23]
Uncertain as to what it means, but I get this error when attempting to run max_utr:

`> max <- max_utr(exp, threshold = 3, feature_type = "geneId")
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "NULL"`

**Comment by rpolicastro** [comment]
Should be fixed with the latest commits

https://github.com/rpolicastro/tsrexplorer/commit/3cb5a31cc491ec9cf8f1bec686e6615caf25369d
https://github.com/rpolicastro/tsrexplorer/commit/c83f6fe5a3e87c63f1e0d0826c0e68e88415bc33
https://github.com/rpolicastro/tsrexplorer/commit/489783dd899127a1ed4c60966b0fc11a52d118d2
